### ISSUE TITLE
Crash Report: Uncaught UnsupportedDrawOperation: s

### ISSUE THREAD

**Issue by phsiao2000** [gre/diaporama-maker#36]
Chrome Version 46.0.2490.80 (64-bit), Mac OS X 10.11.1 (El Capitan)
I'm sure this worked last time I checked this page, pre-El Capitan.

If I move my mouse down to the timeline the error message becomes: `Uncaught TypeError: Cannot read property 'getDOMNode' of undefined`
**Version:**
```
0.5.0
```
**Log detail:**
```
Uncaught UnsupportedDrawOperation: s
Uncaught UnsupportedDrawOperation: s
```

**Comment by gre** [comment]
Fixed. that happens everyone someone "breaks" the demo page, I need to add a way to prevent this later

**Comment by phsiao2000** [comment]
Could you fix it again? I think I must have over-written your fixes because I was still on the page. Thanks!

**Comment by gre** [comment]
done. you can always install diaporama maker with `npm install -g diaporama-maker` if you want to run it locally
