### ISSUE TITLE
Crash Report: Uncaught UnsupportedDrawOperation: fillTasdasdext

### ISSUE THREAD

**Issue by dirkk0** [gre/diaporama-maker#37]
<Provide any extra detail>

**Version:**
```
0.5.0
```
**Log detail:**
```
Uncaught UnsupportedDrawOperation: fillTasdasdext
Uncaught UnsupportedDrawOperation: fillTasdasdext
```

**Comment by gre** [comment]
it was a bug in the demo data. I've done a script that will not clean the demo data every 10min so this does not break the demo forever.
